name: Run Selenium Script

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium-recaptcha-solver
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        
        # Install Google Chrome
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        
        # Get ChromeDriver version that matches Chrome version
        CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$(echo $CHROME_VERSION | cut -d. -f1,2,3))
        
        # Download and install the correct version of ChromeDriver
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /tmp
        sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium script
      env:
        DISPLAY: :99
      run: |
        Xvfb :99 -screen 0 1920x1080x16 &
        python x.py
